# Generated by Django 5.2.1 on 2025-06-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='complete',
        ),
    ]
